# Generated by Django 5.2.3 on 2025-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Иванов', max_length=100),
            preserve_default=False,
        ),
    ]
